In [6]:
board = [[" " for _ in range(3)] for _ in range(3)] 

def print_board(): 
    for row in board: 
        print(" | ".join(row)) 
        print("-" * 5) 
""" Function to check for a win (checks if the current player has won by checking rows, columns, and diagonals.) """
def check_win(player): 
    for i in range(3): 
        """ Check rows and columns """
        if all([board[i][j] == player for j in range(3)]) or all([board[j][i] == player for j in range(3)]): 
            return True 
    # Check diagonals 
    if board[0][0] == board[1][1] == board[2][2] == player      or board[0][2] == board[1][1] == board[2][0] == player: 
        return True 
    return False 
# Function to check if the board is full (draw), (checks if the board is full (no empty spaces left) and no player has  won, which results in a draw.) 
def is_full(): 
    return all(cell != " " for row in board for cell in row)
# Function to handle the player's move (ask the current player to input row and column (0-2).it checks if the selected cell is empty before placing the player symbol) 
def player_move(player): 
    while True: 
        row, col = map(int, input(f"Player {player}, enter row and column (0-2): ").split()) 
        if board[row][col] == " ": 
            board[row][col] = player 
            break 
        print("Cell is already occupied! Try again.") 
 
# Main game loop 
def play_game(): 
    player = "X" 
    while True: 
        print_board() 
        player_move(player) 
        if check_win(player): 
            print_board() 
            print(f"Player {player} wins!") 
            break 
        if is_full(): 
            print_board() 
            print("It's a draw!") 
            break 
        player = "O" if player == "X" else "X"  # Switch players 
play_game()   

  |   |  
-----
  |   |  
-----
  |   |  
-----
Player X, enter row and column (0-2): 0 1
  | X |  
-----
  |   |  
-----
  |   |  
-----
Player O, enter row and column (0-2): 2 0
  | X |  
-----
  |   |  
-----
O |   |  
-----
Player X, enter row and column (0-2): 1 1
  | X |  
-----
  | X |  
-----
O |   |  
-----
Player O, enter row and column (0-2): 2 1
  | X |  
-----
  | X |  
-----
O | O |  
-----
Player X, enter row and column (0-2): 2 2
  | X |  
-----
  | X |  
-----
O | O | X
-----
Player O, enter row and column (0-2): 0 0
O | X |  
-----
  | X |  
-----
O | O | X
-----
Player X, enter row and column (0-2): 1 0
O | X |  
-----
X | X |  
-----
O | O | X
-----
Player O, enter row and column (0-2): 1 2
O | X |  
-----
X | X | O
-----
O | O | X
-----
Player X, enter row and column (0-2): 0 2
O | X | X
-----
X | X | O
-----
O | O | X
-----
It's a draw!


# connect four


In [5]:
import numpy as np

# Constants
ROW_COUNT = 6
COLUMN_COUNT = 7

# Create the board
def create_board():
    return np.zeros((ROW_COUNT, COLUMN_COUNT))

# Drop a piece in the board
def drop_piece(board, row, col, piece):
    board[row][col] = piece

# Check if the column is valid for a move
def is_valid_location(board, col):
    return board[ROW_COUNT - 1][col] == 0

# Get the next open row in the column
def get_next_open_row(board, col):
    for r in range(ROW_COUNT):
        if board[r][col] == 0:
            return r

# Print the board
def print_board(board):
    print(np.flip(board, 0))

# Check for a win condition
def winning_move(board, piece):
    # Check horizontal locations
    for c in range(COLUMN_COUNT - 3):
        for r in range(ROW_COUNT):
            if (board[r][c] == piece and board[r][c + 1] == piece and 
                board[r][c + 2] == piece and board[r][c + 3] == piece):
                return True

    # Check vertical locations
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT - 3):
            if (board[r][c] == piece and board[r + 1][c] == piece and 
                board[r + 2][c] == piece and board[r + 3][c] == piece):
                return True

    # Check positively sloped diagonals
    for c in range(COLUMN_COUNT - 3):
        for r in range(ROW_COUNT - 3):
            if (board[r][c] == piece and board[r + 1][c + 1] == piece and 
                board[r + 2][c + 2] == piece and board[r + 3][c + 3] == piece):
                return True

    # Check negatively sloped diagonals
    for c in range(COLUMN_COUNT - 3):
        for r in range(3, ROW_COUNT):
            if (board[r][c] == piece and board[r - 1][c + 1] == piece and 
                board[r - 2][c + 2] == piece and board[r - 3][c + 3] == piece):
                return True

# Main function to run the game
def play_game():
    board = create_board()
    game_over = False
    turn = 0
    
    print_board(board)

    while not game_over:
        # Ask for Player Input
        if turn == 0:
            col = int(input("Player 1 Make your Selection (0-6): ")) 
            piece = 1
        else:
            col = int(input("Player 2 Make your Selection (0-6): ")) 
            piece = 2

        if is_valid_location(board, col):
            row = get_next_open_row(board, col)
            drop_piece(board, row, col, piece)

            if winning_move(board, piece):
                print_board(board)
                print(f"Player {piece} wins!")
                game_over = True
        
        print_board(board)
        turn += 1
        turn %= 2

# Start the game
if __name__ == "__main__":
    play_game()


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
Player 1 Make your Selection (0-6): 3
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
Player 2 Make your Selection (0-6): 6
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 2.]]
Player 1 Make your Selection (0-6): 1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 2.]]
Player 2 Make your Selection (0-6): 2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 1. 0. 0. 2.]]
Player 1 Make your Selection (0-6): 0
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0.

IndexError: index 7 is out of bounds for axis 0 with size 7

In [3]:
import math
import random

# Initialize board (8x8)
def create_board():
    board = [[" " for _ in range(8)] for _ in range(8)]
    board[3][3], board[4][4] = "O", "O"
    board[3][4], board[4][3] = "X", "X"
    return board

# Display board
def print_board(board):
    print("  " + " ".join(str(i) for i in range(8)))
    for idx, row in enumerate(board):
        print(idx, " ".join(row))

# Directions (8 neighbors)
DIRECTIONS = [(-1,-1), (-1,0), (-1,1),
              (0,-1),         (0,1),
              (1,-1),  (1,0), (1,1)]

# Check if move is valid
def is_valid_move(board, row, col, player):
    if board[row][col] != " ":
        return False
    opponent = "O" if player == "X" else "X"
    flips = []
    for dr, dc in DIRECTIONS:
        r, c = row+dr, col+dc
        line = []
        while 0 <= r < 8 and 0 <= c < 8 and board[r][c] == opponent:
            line.append((r,c))
            r += dr
            c += dc
        if line and 0 <= r < 8 and 0 <= c < 8 and board[r][c] == player:
            flips.extend(line)
    return flips if flips else False

# Get all valid moves
def valid_moves(board, player):
    moves = []
    for r in range(8):
        for c in range(8):
            if is_valid_move(board, r, c, player):
                moves.append((r,c))
    return moves

# Apply move
def make_move(board, row, col, player):
    flips = is_valid_move(board, row, col, player)
    if not flips:
        return False
    board[row][col] = player
    for r,c in flips:
        board[r][c] = player
    return True

# Evaluation: disc difference
def evaluate_board(board):
    x_count = sum(row.count("X") for row in board)
    o_count = sum(row.count("O") for row in board)
    return x_count - o_count

# Alpha-beta search
def alphabeta(board, depth, alpha, beta, maximizing_player):
    if depth == 0 or is_game_over(board):
        return evaluate_board(board), None

    player = "X" if maximizing_player else "O"
    moves = valid_moves(board, player)
    if not moves:
        return evaluate_board(board), None

    best_move = None
    if maximizing_player:  # Human
        max_eval = -math.inf
        for move in moves:
            new_board = [row[:] for row in board]
            make_move(new_board, move[0], move[1], player)
            eval, _ = alphabeta(new_board, depth-1, alpha, beta, False)
            if eval > max_eval:
                max_eval = eval
                best_move = move
            alpha = max(alpha, eval)
            if beta <= alpha:
                break
        return max_eval, best_move
    else:  # AI
        min_eval = math.inf
        for move in moves:
            new_board = [row[:] for row in board]
            make_move(new_board, move[0], move[1], player)
            eval, _ = alphabeta(new_board, depth-1, alpha, beta, True)
            if eval < min_eval:
                min_eval = eval
                best_move = move
            beta = min(beta, eval)
            if beta <= alpha:
                break
        return min_eval, best_move

# Check if game is over
def is_game_over(board):
    return not valid_moves(board, "X") and not valid_moves(board, "O")

# Main game loop
def play_game():
    board = create_board()
    current_player = "X"  # Human goes first

    while not is_game_over(board):
        print_board(board)
        moves = valid_moves(board, current_player)

        if not moves:
            print(f"{current_player} has no valid moves, skipping turn.")
            current_player = "O" if current_player == "X" else "X"
            continue

        if current_player == "X":
            print("Your turn! Valid moves:", moves)
            try:
                row, col = map(int, input("Enter row and col (e.g., 2 3): ").split())
                if (row, col) in moves:
                    make_move(board, row, col, "X")
                    current_player = "O"
                else:
                    print("Invalid move, try again.")
            except:
                print("Invalid input, try again.")
        else:
            print("AI thinking...")
            _, move = alphabeta(board, depth=3, alpha=-math.inf, beta=math.inf, maximizing_player=False)
            if move:
                make_move(board, move[0], move[1], "O")
                print(f"AI plays: {move}")
            current_player = "X"

    # Final board
    print_board(board)
    score = evaluate_board(board)
    if score > 0:
        print("You win!")
    elif score < 0:
        print("AI wins!")
    else:
        print("It's a draw!")

# Run the game
play_game()


  0 1 2 3 4 5 6 7
0                
1                
2                
3       O X      
4       X O      
5                
6                
7                
Your turn! Valid moves: [(2, 3), (3, 2), (4, 5), (5, 4)]


Enter row and col (e.g., 2 3):  5 4


  0 1 2 3 4 5 6 7
0                
1                
2                
3       O X      
4       X X      
5         X      
6                
7                
AI thinking...
AI plays: (3, 5)
  0 1 2 3 4 5 6 7
0                
1                
2                
3       O O O    
4       X X      
5         X      
6                
7                
Your turn! Valid moves: [(2, 2), (2, 3), (2, 4), (2, 5), (2, 6)]


Enter row and col (e.g., 2 3):  7 7


Invalid move, try again.
  0 1 2 3 4 5 6 7
0                
1                
2                
3       O O O    
4       X X      
5         X      
6                
7                
Your turn! Valid moves: [(2, 2), (2, 3), (2, 4), (2, 5), (2, 6)]


Enter row and col (e.g., 2 3):  2 6


  0 1 2 3 4 5 6 7
0                
1                
2             X  
3       O O X    
4       X X      
5         X      
6                
7                
AI thinking...
AI plays: (3, 6)
  0 1 2 3 4 5 6 7
0                
1                
2             X  
3       O O O O  
4       X X      
5         X      
6                
7                
Your turn! Valid moves: [(2, 2), (2, 3), (2, 4), (2, 5), (4, 6)]


Enter row and col (e.g., 2 3):  4 6


  0 1 2 3 4 5 6 7
0                
1                
2             X  
3       O O O X  
4       X X   X  
5         X      
6                
7                
AI thinking...
AI plays: (3, 7)
  0 1 2 3 4 5 6 7
0                
1                
2             X  
3       O O O O O
4       X X   X  
5         X      
6                
7                
Your turn! Valid moves: [(2, 2), (2, 3), (2, 4), (2, 5)]


Enter row and col (e.g., 2 3):  2 5


  0 1 2 3 4 5 6 7
0                
1                
2           X X  
3       O X O O O
4       X X   X  
5         X      
6                
7                
AI thinking...
AI plays: (1, 4)
  0 1 2 3 4 5 6 7
0                
1         O      
2           O X  
3       O X O O O
4       X X   X  
5         X      
6                
7                
Your turn! Valid moves: [(1, 6), (2, 2), (2, 3), (2, 4), (3, 2)]


Enter row and col (e.g., 2 3):  3 2


  0 1 2 3 4 5 6 7
0                
1         O      
2           O X  
3     X X X O O O
4       X X   X  
5         X      
6                
7                
AI thinking...
AI plays: (3, 1)
  0 1 2 3 4 5 6 7
0                
1         O      
2           O X  
3   O O O O O O O
4       X X   X  
5         X      
6                
7                
Your turn! Valid moves: [(1, 6), (2, 1), (2, 2), (2, 3), (2, 4)]


Enter row and col (e.g., 2 3):  2 4


  0 1 2 3 4 5 6 7
0                
1         O      
2         X X X  
3   O O O X X O O
4       X X   X  
5         X      
6                
7                
AI thinking...
AI plays: (1, 5)
  0 1 2 3 4 5 6 7
0                
1         O O    
2         O X O  
3   O O O X X O O
4       X X   X  
5         X      
6                
7                
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (1, 3), (1, 6), (1, 7), (2, 1), (2, 2), (2, 3), (2, 7), (3, 0), (4, 7)]


Enter row and col (e.g., 2 3):  1 3


  0 1 2 3 4 5 6 7
0                
1       X O O    
2         X X O  
3   O O O X X O O
4       X X   X  
5         X      
6                
7                
AI thinking...
AI plays: (5, 3)
  0 1 2 3 4 5 6 7
0                
1       X O O    
2         X X O  
3   O O O X O O O
4       O O   X  
5       O X      
6                
7                
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 6), (1, 6), (2, 1), (2, 7), (3, 0), (4, 2), (4, 5), (4, 7), (5, 2)]


Enter row and col (e.g., 2 3):  2 7


  0 1 2 3 4 5 6 7
0                
1       X O O    
2         X X X X
3   O O O X O O O
4       O O   X  
5       O X      
6                
7                
AI thinking...
AI plays: (1, 6)
  0 1 2 3 4 5 6 7
0                
1       X O O O  
2         X O O X
3   O O O O O O O
4       O O   X  
5       O X      
6                
7                
Your turn! Valid moves: [(0, 4), (0, 5), (0, 6), (1, 7), (2, 1), (4, 2), (4, 5), (4, 7), (5, 2)]


Enter row and col (e.g., 2 3):  5 2


  0 1 2 3 4 5 6 7
0                
1       X O O O  
2         X O O X
3   O O O O O O O
4       O O   X  
5     X X X      
6                
7                
AI thinking...
AI plays: (0, 2)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2         O O O X
3   O O O O O O O
4       O O   X  
5     X X X      
6                
7                
Your turn! Valid moves: [(0, 4), (0, 5), (0, 6), (0, 7), (1, 7), (2, 1), (2, 3), (4, 5), (4, 7)]


Enter row and col (e.g., 2 3):  4 5


  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2         O O O X
3   O O O O O X O
4       O O X X  
5     X X X      
6                
7                
AI thinking...
AI plays: (4, 7)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2         O O O X
3   O O O O O O O
4       O O O O O
5     X X X      
6                
7                
Your turn! Valid moves: [(0, 4), (0, 5), (0, 7), (1, 7), (2, 1), (2, 3), (5, 7)]


Enter row and col (e.g., 2 3):  5 7


  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2         O O O X
3   O O O O O O X
4       O O O O X
5     X X X     X
6                
7                
AI thinking...
AI plays: (6, 3)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2         O O O X
3   O O O O O O X
4       O O O O X
5     X O O     X
6       O        
7                
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 7), (2, 3), (3, 0), (4, 2), (5, 5), (7, 2), (7, 4)]


Enter row and col (e.g., 2 3):  4 2


  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2         O O O X
3   O O O O O O X
4     X X X X X X
5     X O O     X
6       O        
7                
AI thinking...
AI plays: (5, 6)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2         O O O X
3   O O O O O O X
4     X X X O O X
5     X O O   O X
6       O        
7                
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (5, 5), (6, 2), (6, 4), (6, 5), (7, 2), (7, 3), (7, 4)]


Enter row and col (e.g., 2 3):  2 1


  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2   X     O O O X
3   O X O O O O X
4     X X X O O X
5     X O O   O X
6       O        
7                
AI thinking...
AI plays: (4, 1)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2   X     O O O X
3   O X O O O O X
4   O O O O O O X
5     O O O   O X
6       O        
7                
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (2, 3), (3, 0), (4, 0), (5, 0), (5, 1), (5, 5), (6, 2), (6, 5), (7, 2)]


Enter row and col (e.g., 2 3):  2 3


  0 1 2 3 4 5 6 7
0     O          
1       O O O O  
2   X   X X X X X
3   O X O O O O X
4   O O O O O O X
5     O O O   O X
6       O        
7                
AI thinking...
AI plays: (1, 7)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X   X X X O X
3   O X O O O O X
4   O O O O O O X
5     O O O   O X
6       O        
7                
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (3, 0), (4, 0), (5, 0), (5, 1), (5, 5), (6, 1), (6, 2), (6, 4), (6, 5), (6, 7), (7, 2), (7, 3)]


Enter row and col (e.g., 2 3):  5 5


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X   X X X O X
3   O X O O X O X
4   O O O O X X X
5     O O O X X X
6       O        
7                
AI thinking...
AI plays: (6, 7)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X   X X X O O
3   O X O O X O O
4   O O O O O X O
5     O O O X O O
6       O       O
7                
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (2, 2), (3, 0), (4, 0), (5, 0), (5, 1), (6, 1), (6, 2), (6, 4), (6, 5), (6, 6), (7, 3)]


Enter row and col (e.g., 2 3):  6 2


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X   X X X O O
3   O X O O X O O
4   O X O X O X O
5     X X O X O O
6     X O       O
7                
AI thinking...
AI plays: (7, 1)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X   X X X O O
3   O X O O O O O
4   O X O O O X O
5     X O O X O O
6     O O       O
7   O            
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (2, 0), (2, 2), (3, 0), (4, 0), (5, 0), (5, 1), (6, 4), (6, 5), (6, 6), (7, 2), (7, 3), (7, 4)]


Enter row and col (e.g., 2 3):  5 1


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X   X X X O O
3   X X O O O O O
4   X X O O O X O
5   X X O O X O O
6     O O       O
7   O            
AI thinking...
AI plays: (4, 0)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X   X X X O O
3   X X O O O O O
4 O O O O O O X O
5   O X O O X O O
6     O O       O
7   O            
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (2, 2), (3, 0), (5, 0), (6, 0), (6, 1), (6, 4), (6, 5), (6, 6), (7, 2), (7, 3), (7, 4)]


Enter row and col (e.g., 2 3):  2 2


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X X X X X O O
3   X X X O O O O
4 O O O O X O X O
5   O X O O X O O
6     O O       O
7   O            
AI thinking...
AI plays: (3, 0)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X X X X X O O
3 O O O O O O O O
4 O O O O X O X O
5   O X O O X O O
6     O O       O
7   O            
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (5, 0), (6, 0), (6, 1), (6, 4), (6, 5), (6, 6), (7, 2), (7, 3), (7, 4)]


Enter row and col (e.g., 2 3):  6 6


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2   X X X X X O O
3 O O O O O O O O
4 O O O O X O X O
5   O X O O X X O
6     O O     X O
7   O            
AI thinking...
AI plays: (2, 0)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O X O
5   O X O O X X O
6     O O     X O
7   O            
Your turn! Valid moves: [(0, 4), (0, 5), (0, 6), (0, 7), (1, 1), (1, 2), (5, 0), (6, 4), (7, 2), (7, 4)]


Enter row and col (e.g., 2 3):  5 0


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O X O
5 X X X O O X X O
6     O O     X O
7   O            
AI thinking...
AI plays: (6, 0)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O X O
5 O O X O O X X O
6 O   O O     X O
7   O            
Your turn! Valid moves: [(0, 4), (0, 5), (0, 6), (0, 7), (1, 1), (1, 2), (6, 4), (7, 2), (7, 4)]


Enter row and col (e.g., 2 3):  7 4


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O X O
5 O O X O O X X O
6 O   O X     X O
7   O     X      
AI thinking...
AI plays: (6, 4)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O X O O O X O
6 O   O O O   X O
7   O     X      
Your turn! Valid moves: [(0, 4), (0, 6), (0, 7), (1, 1), (1, 2), (7, 2)]


Enter row and col (e.g., 2 3):  7 2


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O X O O O X O
6 O   X O O   X O
7   O X   X      
AI thinking...
AI plays: (6, 5)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O X O O O O O
6 O   X O O O O O
7   O X   X      
Your turn! Valid moves: [(0, 4), (0, 7), (1, 1), (1, 2), (7, 0), (7, 7)]


Enter row and col (e.g., 2 3):  7 7


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O X O O X O O
6 O   X O O O X O
7   O X   X     X
AI thinking...
AI plays: (6, 1)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O O O O X O O
6 O O O O O O X O
7   O X   X     X
Your turn! Valid moves: [(0, 4), (0, 5), (0, 6), (0, 7), (1, 1), (1, 2), (7, 0), (7, 3), (7, 5)]


Enter row and col (e.g., 2 3):  7 5


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O O O O X O O
6 O O O O O X X O
7   O X   X X   X
AI thinking...
AI plays: (7, 3)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O O O O X O O
6 O O O O O X X O
7   O O O X X   X
Your turn! Valid moves: [(0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (7, 0)]


Enter row and col (e.g., 2 3):  7 0


  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O O O O X O O
6 O O O O O X X O
7 X X X X X X   X
AI thinking...
AI plays: (7, 6)
  0 1 2 3 4 5 6 7
0     O          
1       O O O O O
2 O O O O O O O O
3 O O O O O O O O
4 O O O O X O O O
5 O O O O O X O O
6 O O O O O O O O
7 X X X X X X O X
Your turn! Valid moves: [(0, 3), (0, 4), (0, 5), (0, 7), (1, 0), (1, 1), (1, 2)]


Enter row and col (e.g., 2 3):  1 2


  0 1 2 3 4 5 6 7
0     O          
1     X O O O O O
2 O O X O O O O O
3 O O X O O O O O
4 O O X O X O O O
5 O O X O O X O O
6 O O X O O O O O
7 X X X X X X O X
AI thinking...
AI plays: (1, 1)
  0 1 2 3 4 5 6 7
0     O          
1   O O O O O O O
2 O O O O O O O O
3 O O X O O O O O
4 O O X O X O O O
5 O O X O O X O O
6 O O X O O O O O
7 X X X X X X O X
Your turn! Valid moves: [(0, 0), (0, 1), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0)]


Enter row and col (e.g., 2 3):  1 0


  0 1 2 3 4 5 6 7
0     O          
1 X O O O O O O O
2 X X O O O O O O
3 X O X O O O O O
4 X O X O X O O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
O has no valid moves, skipping turn.
  0 1 2 3 4 5 6 7
0     O          
1 X O O O O O O O
2 X X O O O O O O
3 X O X O O O O O
4 X O X O X O O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
Your turn! Valid moves: [(0, 0), (0, 1), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7)]


Enter row and col (e.g., 2 3):  0 6


  0 1 2 3 4 5 6 7
0     O       X  
1 X O O O O X O O
2 X X O O X O O O
3 X O X X O O O O
4 X O X O X O O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
AI thinking...
AI plays: (0, 4)
  0 1 2 3 4 5 6 7
0     O   O   X  
1 X O O O O O O O
2 X X O O X O O O
3 X O X X O O O O
4 X O X O X O O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
Your turn! Valid moves: [(0, 0), (0, 1), (0, 3), (0, 5), (0, 7)]


Enter row and col (e.g., 2 3):  0 0


  0 1 2 3 4 5 6 7
0 X   O   O   X  
1 X X O O O O O O
2 X X X O X O O O
3 X O X X O O O O
4 X O X O X O O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
AI thinking...
AI plays: (0, 1)
  0 1 2 3 4 5 6 7
0 X O O   O   X  
1 X O O O O O O O
2 X O X O X O O O
3 X O X X O O O O
4 X O X O X O O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
Your turn! Valid moves: [(0, 3), (0, 5), (0, 7)]


Enter row and col (e.g., 2 3):  0 5


  0 1 2 3 4 5 6 7
0 X O O   O X X  
1 X O O O X X O O
2 X O X X X X O O
3 X O X X O X O O
4 X O X O X X O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
AI thinking...
AI plays: (0, 7)
  0 1 2 3 4 5 6 7
0 X O O   O O O O
1 X O O O X X O O
2 X O X X X X O O
3 X O X X O X O O
4 X O X O X X O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
Your turn! Valid moves: [(0, 3)]


Enter row and col (e.g., 2 3):  0 3


  0 1 2 3 4 5 6 7
0 X X X X O O O O
1 X O X X X X O O
2 X X X X X X O O
3 X O X X O X O O
4 X O X O X X O O
5 X O X O O X O O
6 X O X O O O O O
7 X X X X X X O X
You win!


In [7]:
pip install pygame


   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
    --------------------------------------- 0.3/10.6 MB ? eta -:--:--
    --------------------------------------- 0.3/10.6 MB ? eta -:--:--
    --------------------------------------- 0.3/10.6 MB ? eta -:--:--
    --------------------------------------- 0.3/10.6 MB ? eta -:--:--
    --------------------------------------- 0.3/10.6 MB ? eta -:--:--
    --------------------------------------- 0.3/10.6 MB ? eta -:--:--
    --------------------------------------- 0.3/10.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.6 MB 167.8 kB/s eta 0:01:01
   - -------------------------------------- 0.5/10.6 MB 167.8 kB/s eta 0:01:01
  

In [ ]:
import numpy as np
import pygame
import sys
import math
import random

from pkg_resources import resource_stream, resource_exists

# Initialize pygame
pygame.init()

ROW_COUNT = 6
COLUMN_COUNT = 7
SQUARESIZE = 100
RADIUS = int(SQUARESIZE / 2 - 5)
width = COLUMN_COUNT * SQUARESIZE
height = (ROW_COUNT + 1) * SQUARESIZE
size = (width, height)

# Colors
BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)

screen = pygame.display.set_mode(size)

def create_board():
    return np.zeros((ROW_COUNT, COLUMN_COUNT))

def draw_board(board):
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):
            pygame.draw.rect(screen, BLUE, (c*SQUARESIZE, r*SQUARESIZE + SQUARESIZE, SQUARESIZE, SQUARESIZE))
            pygame.draw.circle(screen, BLACK, (int(c*SQUARESIZE+SQUARESIZE/2), int(r*SQUARESIZE+SQUARESIZE+SQUARESIZE/2)), RADIUS)

    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT):
            if board[r][c] == 1:
                pygame.draw.circle(screen, RED, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)
            elif board[r][c] == 2:
                pygame.draw.circle(screen, YELLOW, (int(c*SQUARESIZE+SQUARESIZE/2), height-int(r*SQUARESIZE+SQUARESIZE/2)), RADIUS)

    pygame.display.update()

def is_valid_location(board, col):
    return board[ROW_COUNT - 1][col] == 0

def get_next_open_row(board, col):
    for r in range(ROW_COUNT):
        if board[r][col] == 0:
            return r

def drop_piece(board, row, col, piece):
    board[row][col] = piece

def winning_move(board, piece):
    # Horizontal
    for c in range(COLUMN_COUNT - 3):
        for r in range(ROW_COUNT):
            if all(board[r][c+i] == piece for i in range(4)):
                return True
    # Vertical
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT - 3):
            if all(board[r+i][c] == piece for i in range(4)):
                return True
    # Positive diagonal
    for c in range(COLUMN_COUNT - 3):
        for r in range(ROW_COUNT - 3):
            if all(board[r+i][c+i] == piece for i in range(4)):
                return True
    # Negative diagonal
    for c in range(COLUMN_COUNT - 3):
        for r in range(3, ROW_COUNT):
            if all(board[r-i][c+i] == piece for i in range(4)):
                return True
    return False

def evaluate_window(window, piece):
    score = 0
    opp_piece = 1 if piece == 2 else 2
    if window.count(piece) == 4:
        score += 100
    elif window.count(piece) == 3 and window.count(0) == 1:
        score += 5
    elif window.count(piece) == 2 and window.count(0) == 2:
        score += 2
    if window.count(opp_piece) == 3 and window.count(0) == 1:
        score -= 4
    return score

def score_position(board, piece):
    score = 0
    # Center column preference
    center_array = [int(i) for i in list(board[:, COLUMN_COUNT // 2])]
    score += center_array.count(piece) * 3
    # Horizontal
    for r in range(ROW_COUNT):
        row_array = [int(i) for i in list(board[r,:])]
        for c in range(COLUMN_COUNT - 3):
            score += evaluate_window(row_array[c:c+4], piece)
    # Vertical
    for c in range(COLUMN_COUNT):
        col_array = [int(i) for i in list(board[:,c])]
        for r in range(ROW_COUNT - 3):
            score += evaluate_window(col_array[r:r+4], piece)
    # Diagonals
    for r in range(ROW_COUNT - 3):
        for c in range(COLUMN_COUNT - 3):
            window = [board[r+i][c+i] for i in range(4)]
            score += evaluate_window(window, piece)
            window = [board[r+3-i][c+i] for i in range(4)]
            score += evaluate_window(window, piece)
    return score

def minimax(board, depth, alpha, beta, maximizingPlayer):
    valid_locations = [c for c in range(COLUMN_COUNT) if is_valid_location(board, c)]
    is_terminal = winning_move(board, 1) or winning_move(board, 2) or len(valid_locations) == 0
    if depth == 0 or is_terminal:
        if is_terminal:
            if winning_move(board, 2): return (None, 100000000000000)
            elif winning_move(board, 1): return (None, -10000000000000)
            else: return (None, 0)
        else:
            return (None, score_position(board, 2))

    if maximizingPlayer:
        value = -math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            b_copy = board.copy()
            drop_piece(b_copy, row, col, 2)
            new_score = minimax(b_copy, depth-1, alpha, beta, False)[1]
            if new_score > value:
                value = new_score
                column = col
            alpha = max(alpha, value)
            if alpha >= beta:
                break
        return column, value
    else:
        value = math.inf
        column = random.choice(valid_locations)
        for col in valid_locations:
            row = get_next_open_row(board, col)
            b_copy = board.copy()
            drop_piece(b_copy, row, col, 1)
            new_score = minimax(b_copy, depth-1, alpha, beta, True)[1]
            if new_score < value:
                value = new_score
                column = col
            beta = min(beta, value)
            if alpha >= beta:
                break
        return column, value

# Main game loop
board = create_board()
game_over = False
turn = 0
draw_board(board)

while not game_over:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()

        if event.type == pygame.MOUSEMOTION:
            pygame.draw.rect(screen, BLACK, (0, 0, width, SQUARESIZE))
            posx = event.pos[0]
            if turn == 0:
                pygame.draw.circle(screen, RED, (posx, int(SQUARESIZE/2)), RADIUS)
            else:
                pygame.draw.circle(screen, YELLOW, (posx, int(SQUARESIZE/2)), RADIUS)
            pygame.display.update()

        if event.type == pygame.MOUSEBUTTONDOWN:
            pygame.draw.rect(screen, BLACK, (0, 0, width, SQUARESIZE))
            if turn == 0:  # Player
                posx = event.pos[0]
                col = int(math.floor(posx / SQUARESIZE))
                if is_valid_location(board, col):
                    row = get_next_open_row(board, col)
                    drop_piece(board, row, col, 1)
                    if winning_move(board, 1):
                        print("PLAYER WINS!")
                        game_over = True
            else:  # AI
                col, minimax_score = minimax(board, 4, -math.inf, math.inf, True)
                if is_valid_location(board, col):
                    row = get_next_open_row(board, col)
                    drop_piece(board, row, col, 2)
                    if winning_move(board, 2):
                        print("AI WINS!")
                        game_over = True
            draw_board(board)
            turn = (turn + 1) % 2


In [11]:
import pygame
import sys

pygame.init()
WIDTH, HEIGHT = 800, 800
SQUARE_SIZE = WIDTH // 8
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption('Chess')

# Colors
WHITE = (232, 235, 239)
BLACK = (125, 135, 150)

# All chess pieces we need images for (two letters: color + type)
pieces = [
    "wp", "wR", "wN", "wB", "wQ", "wK", 
    "bp", "bR", "bN", "bB", "bQ", "bK"
]

def load_images():
    images = {}
    for piece in pieces:
        try:
            images[piece] = pygame.transform.scale(
                pygame.image.load(f'images/{piece}.png'), 
                (SQUARE_SIZE, SQUARE_SIZE)
            )
        except:
            print(f"Missing image for {piece}, using empty placeholder.")
            surf = pygame.Surface((SQUARE_SIZE, SQUARE_SIZE))
            surf.fill((200, 200, 200))
            images[piece] = surf
    return images

images = load_images()

def draw_board(screen):
    colors = [WHITE, BLACK]
    for row in range(8):
        for col in range(8):
            color = colors[(row + col) % 2]
            pygame.draw.rect(screen, color, 
                pygame.Rect(col*SQUARE_SIZE, row*SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE))

def draw_pieces(screen, board):
    for row in range(8):
        for col in range(8):
            piece = board[row][col]
            if piece != '--':
                screen.blit(images[piece], 
                    pygame.Rect(col*SQUARE_SIZE, row*SQUARE_SIZE, SQUARE_SIZE, SQUARE_SIZE))

def create_board():
    # Standard chess starting position
    return [
        ["bR","bN","bB","bQ","bK","bB","bN","bR"],
        ["bp","bp","bp","bp","bp","bp","bp","bp"],
        ["--","--","--","--","--","--","--","--"],
        ["--","--","--","--","--","--","--","--"],
        ["--","--","--","--","--","--","--","--"],
        ["--","--","--","--","--","--","--","--"],
        ["wp","wp","wp","wp","wp","wp","wp","wp"],
        ["wR","wN","wB","wQ","wK","wB","wN","wR"]
    ]

board = create_board()

def main():
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        draw_board(screen)
        draw_pieces(screen, board)
        pygame.display.flip()

    pygame.quit()
    sys.exit()

if __name__ == "__main__":
    main()


Missing image for wp, using empty placeholder.
Missing image for wR, using empty placeholder.
Missing image for wN, using empty placeholder.
Missing image for wB, using empty placeholder.
Missing image for wQ, using empty placeholder.
Missing image for wK, using empty placeholder.
Missing image for bp, using empty placeholder.
Missing image for bR, using empty placeholder.
Missing image for bN, using empty placeholder.
Missing image for bB, using empty placeholder.
Missing image for bQ, using empty placeholder.
Missing image for bK, using empty placeholder.


KeyboardInterrupt: 